apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: <NAMESPACE>
  name: knative-serving-monolith
spec:
  template:
    spec:
      containers:
        - image: <DOCKER_IMAGE>
          ports:
            - containerPort: 8080
          env:
            - name: db.connection_string
              value: >-
                jdbc:postgresql://postgres.<NAMESPACE>.svc.cluster.local:5432/knative_demo